# This file was generated by GoReleaser. DO NOT EDIT.
class Fuzzit < Formula
  desc "Continuous Fuzzing Made Simple."
  homepage "https://fuzzit.dev"
  version "2.4.49"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.49/fuzzit_Darwin_x86_64.zip"
    sha256 "5dc2d79f9b0effa762a3255c6721f248f2eaf228655d7ac141eb295b38a34744"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.49/fuzzit_Linux_x86_64.zip"
      sha256 "f1a1787e3d75b7ada3975231557ec4899aca87978d122f2cc7244c9202892bdc"
    end
  end

  def install
    bin.install "fuzzit"
  end
end
