# This file was generated by GoReleaser. DO NOT EDIT.
class Fuzzit < Formula
  desc "Continuous Fuzzing Made Simple."
  homepage "https://fuzzit.dev"
  version "2.4.54"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.54/fuzzit_Darwin_x86_64.zip"
    sha256 "509b599ef530f41364ef0909303a0cd058b5baa0117b71aadfd2e09db3da478d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.54/fuzzit_Linux_x86_64.zip"
      sha256 "05af5f72b65ec5c6c710b1abf00c5a531e2b91b83aba4930bfdf7170324a9c8a"
    end
  end

  def install
    bin.install "fuzzit"
  end
end
